# Generated by Django 5.2.9 on 2026-01-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmeta',
            name='languages',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectmeta',
            name='tests',
            field=models.TextField(blank=True, default=''),
        ),
    ]
