# Generated by Django 5.2.9 on 2026-01-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectmeta_languages_alter_projectmeta_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmeta',
            name='intern_name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
