# Generated by Django 5.2.9 on 2026-05-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectmeta_intern_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmeta',
            name='icon',
            field=models.CharField(blank=True, default='layers', help_text='Feather icon name, for example: user-check, briefcase, target, bar-chart-2', max_length=50),
        ),
    ]
