# Generated by Django 5.2.9 on 2026-02-15 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0015_remove_userorgunitaccess_permission_level_and_more'),
        ('processes', '0018_testprocess_archived_at_testprocess_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, default='', max_length=255)),
                ('verb', models.CharField(choices=[('process_created', 'Process skapad'), ('candidate_added', 'Kandidat lades till i process'), ('invite_sent', 'Inbjudan skickad'), ('status_changed', 'Status ändrad')], max_length=50)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='processes.candidate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='accounts.company')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='processes.testinvitation')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='processes.testprocess')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='activity_ac_company_071b2b_idx'), models.Index(fields=['process', '-created_at'], name='activity_ac_process_289f84_idx'), models.Index(fields=['candidate', '-created_at'], name='activity_ac_candida_c662db_idx'), models.Index(fields=['invitation', '-created_at'], name='activity_ac_invitat_99173b_idx'), models.Index(fields=['verb', '-created_at'], name='activity_ac_verb_b8bc63_idx')],
            },
        ),
    ]
