# Generated by Django 5.2.9 on 2026-02-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='verb',
            field=models.CharField(choices=[('process_created', 'Process skapad'), ('process_archived', 'Process arkiverad'), ('process_deleted', 'Process raderad'), ('candidate_added', 'Kandidat lades till i process'), ('candidate_removed', 'Kandidat togs bort från process'), ('invite_sent', 'Inbjudan skickad'), ('status_changed', 'Status ändrad')], max_length=50),
        ),
    ]
