# Generated by Django 5.2.9 on 2026-05-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activityevent_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='verb',
            field=models.CharField(choices=[('process_created', 'Process skapad'), ('process_archived', 'Process arkiverad'), ('process_deleted', 'Process raderad'), ('candidate_added', 'Kandidat lades till i process'), ('candidate_removed', 'Kandidat togs bort från process'), ('invite_sent', 'Inbjudan skickad'), ('test_started', 'Test påbörjat'), ('test_completed', 'Test slutfört'), ('all_tests_completed', 'Alla tester slutförda'), ('status_changed', 'Status ändrad')], max_length=50),
        ),
    ]
