# Generated by Django 5.2.9 on 2026-05-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activityevent_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='verb',
            field=models.CharField(choices=[('process_created', 'Process skapad'), ('process_archived', 'Process arkiverad'), ('process_deleted', 'Process raderad'), ('candidate_added', 'Kandidat lades till i process'), ('candidate_removed', 'Kandidat togs bort från process'), ('invite_sent', 'Testinbjudan skickad'), ('test_started', 'Test påbörjat'), ('test_completed', 'Test slutfört'), ('all_tests_completed', 'Alla tester slutförda'), ('status_changed', 'Status ändrad'), ('company_created', 'Företag skapat'), ('company_updated', 'Företag uppdaterat'), ('company_deleted', 'Företag raderat'), ('company_member_invited', 'Användare inbjuden'), ('company_member_added', 'Användare tillagd'), ('company_member_removed', 'Användare borttagen'), ('company_member_role_updated', 'Användarroll uppdaterad'), ('company_invite_accepted', 'Inbjudan accepterad'), ('orgunit_created', 'Konto/enhet skapad'), ('orgunit_updated', 'Konto/enhet uppdaterad'), ('orgunit_moved', 'Konto/enhet flyttad'), ('orgunit_deleted', 'Konto/enhet raderad'), ('user_access_updated', 'Användaråtkomst uppdaterad'), ('user_logged_in', 'Användare loggade in')], max_length=80),
        ),
    ]
