# Generated by Django 5.2.9 on 2026-01-30 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_backfill_company_and_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccountaccess',
            options={},
        ),
        migrations.RemoveField(
            model_name='useraccountaccess',
            name='role',
        ),
        migrations.AlterField(
            model_name='useraccountaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='useraccountaccess',
            constraint=models.UniqueConstraint(fields=('user', 'account'), name='uniq_user_account'),
        ),
    ]
