# Generated by Django 5.2.9 on 2026-02-02 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountaccess',
            name='account',
        ),
        migrations.RemoveField(
            model_name='useraccountaccess',
            name='user',
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Enhetsnamn')),
                ('unit_code', models.CharField(help_text='T.ex. CAPITOL, D12, D01', max_length=50, verbose_name='Enhetskod')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_units', to='accounts.company', verbose_name='Företag')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.orgunit', verbose_name='Överliggande enhet')),
            ],
            options={
                'verbose_name': 'Org unit',
                'verbose_name_plural': 'Org units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserOrgUnitAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='accounts.orgunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgunit_accesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='UserAccountAccess',
        ),
        migrations.AddConstraint(
            model_name='orgunit',
            constraint=models.UniqueConstraint(fields=('company', 'unit_code'), name='uniq_unit_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='userorgunitaccess',
            constraint=models.UniqueConstraint(fields=('user', 'org_unit'), name='uniq_user_orgunit'),
        ),
    ]
