# Generated by Django 5.2.9 on 2026-02-13 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_useraccountaccess_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymember',
            name='primary_org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_members', to='accounts.orgunit', verbose_name='Primär enhet'),
        ),
    ]
