# Generated by Django 5.2.9 on 2026-02-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_companymember_primary_org_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorgunitaccess',
            name='permission_level',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('own', 'Edit own only')], default='editor', max_length=20),
        ),
    ]
