# Generated by Django 5.2.9 on 2026-02-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userorgunitaccess_permission_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorgunitaccess',
            name='permission_level',
        ),
        migrations.AddField(
            model_name='userorgunitaccess',
            name='permission',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('own', 'Own only')], default='viewer', max_length=10),
        ),
    ]
