# Generated by Django 5.2.9 on 2026-07-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_userorgunitaccess_permission_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], db_index=True, default='customer', max_length=20, verbose_name='Plattformsroll'),
        ),
    ]
