# Generated by Django 6.0.1 on 2026-03-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeentry',
            name='knowledge_type',
            field=models.CharField(choices=[('base', 'Base'), ('tq', 'TQ-expert')], default='base', max_length=20),
        ),
    ]
