# Generated by Django 5.2.9 on 2026-01-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testprocess',
            name='status',
        ),
    ]
