# Generated by Django 5.2.9 on 2026-01-15 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_candidate_testinvitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testinvitation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='testinvitation',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='processes.candidate'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('email',), name='uniq_candidate_email'),
        ),
        migrations.AddConstraint(
            model_name='testinvitation',
            constraint=models.UniqueConstraint(fields=('process', 'candidate'), name='uniq_invitation_per_process'),
        ),
    ]
