# Generated by Django 6.0.1 on 2026-01-21 12:11

import uuid
import django.db.models.deletion
from django.db import migrations, models


def populate_self_registration_tokens(apps, schema_editor):
    TestProcess = apps.get_model("processes", "TestProcess")

    # Fyll token för befintliga rader som saknar token
    for p in TestProcess.objects.filter(self_registration_token__isnull=True):
        p.self_registration_token = uuid.uuid4()
        p.save(update_fields=["self_registration_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_alter_testinvitation_unique_together_and_more'),
    ]

    operations = [
        # 1) Lägg till fältet NULL först (ingen unique ännu)
        migrations.AddField(
            model_name='testprocess',
            name='self_registration_token',
            field=models.UUIDField(null=True, db_index=True, editable=False),
        ),

        # 2) Ge alla befintliga processer en uuid
        migrations.RunPython(populate_self_registration_tokens, migrations.RunPython.noop),

        # 3) Gör fältet strikt: unique + default framåt (och non-null)
        migrations.AlterField(
            model_name='testprocess',
            name='self_registration_token',
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
                editable=False,
                db_index=True,
            ),
        ),

        # Din SelfRegistration-modell kan ligga kvar som den var
        migrations.CreateModel(
            name='SelfRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sova_candidate_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sova_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_registrations', to='processes.testprocess')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('process', 'email'), name='uniq_process_email_registration')],
            },
        ),
    ]


