# Generated by Django 6.0.1 on 2026-01-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_testprocess_self_registration_token_selfregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinvitation',
            name='source',
            field=models.CharField(choices=[('invited', 'Invited'), ('self_registered', 'Self-registered')], default='invited', max_length=20),
        ),
    ]
