# Generated by Django 6.0.1 on 2026-01-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_testinvitation_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinvitation',
            name='assessment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='sova_request_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
