# Generated by Django 6.0.1 on 2026-01-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0008_testinvitation_result_payload_testinvitation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinvitation',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='project_results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='request_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='sova_project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
