# Generated by Django 6.0.1 on 2026-01-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0009_testinvitation_overall_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinvitation',
            name='sova_current_phase_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='sova_current_phase_idx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='sova_overall_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
