# Generated by Django 5.2.9 on 2026-01-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_account_useraccountaccess"),
        ("processes", "0010_testinvitation_sova_current_phase_code_and_more"),
    ]

    operations = [
        # No-op:
        # This migration previously added TestProcess.account pointing to accounts.Account.
        # The current data model uses TestProcess.company pointing to accounts.Company instead.
    ]