# Generated by Django 5.2.9 on 2026-01-29 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_useraccountaccess'),
        ('processes', '0010_testinvitation_sova_current_phase_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testprocess',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_processes', to='accounts.account', verbose_name='Account'),
        ),
    ]
