# Generated by Django 5.2.9 on 2026-01-30 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userinvite'),
        ('processes', '0011_testprocess_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testprocess',
            name='account',
        ),
        migrations.AddField(
            model_name='testprocess',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='accounts.company'),
        ),
    ]
