# Generated by Django 5.2.9 on 2026-02-12 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_useraccountaccess_account_and_more'),
        ('processes', '0014_testprocess_created_by_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_labels', to='accounts.company')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='testprocess',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='processes', to='processes.processlabel'),
        ),
    ]
