# Generated by Django 5.2.9 on 2026-02-12 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_useraccountaccess_account_and_more'),
        ('processes', '0015_processlabel_testprocess_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='testprocess',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_processes', to='accounts.orgunit'),
        ),
    ]
