# Generated by Django 5.2.9 on 2026-02-13 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_companymember_primary_org_unit'),
        ('processes', '0016_testprocess_org_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testprocess',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='accounts.orgunit'),
        ),
    ]
