# Generated by Django 5.2.9 on 2026-02-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0017_alter_testprocess_org_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='testprocess',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testprocess',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
