# Generated by Django 5.2.9 on 2026-02-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0018_testprocess_archived_at_testprocess_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinvitation',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
