# Generated by Django 5.2.9 on 2026-04-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0019_testinvitation_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinvitation',
            name='sova_activities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='sova_phases',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='sova_reports',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
