# Generated by Django 6.0.1 on 2026-04-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0020_testinvitation_sova_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinvitation',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_summary_status',
            field=models.CharField(blank=True, default='not_started', max_length=30),
        ),
    ]
