# Generated by Django 6.0.1 on 2026-05-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0021_testinvitation_ai_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testprocess',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='testprocess',
            name='selected_tests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
