# Generated by Django 6.0.1 on 2026-05-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0022_testprocess_purpose_testprocess_selected_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='testprocess',
            name='sova_project_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
