# Generated by Django 6.0.1 on 2026-05-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0023_testprocess_sova_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testprocess',
            name='sova_project_id',
        ),
    ]
