# Generated by Django 6.0.1 on 2026-05-19 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0024_remove_testprocess_sova_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessRoleContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(blank=True, max_length=255)),
                ('job_advertisement', models.TextField(blank=True)),
                ('requirements_profile', models.TextField(blank=True)),
                ('competency_profile', models.TextField(blank=True)),
                ('must_haves', models.TextField(blank=True)),
                ('nice_to_haves', models.TextField(blank=True)),
                ('priorities', models.TextField(blank=True)),
                ('interview_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_context', to='processes.testprocess')),
            ],
        ),
    ]
