# Generated by Django 5.2.9 on 2026-06-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0025_processrolecontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinvitation',
            name='historical_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='historical_report_file',
            field=models.FileField(blank=True, null=True, upload_to='historical_sova_reports/'),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='historical_report_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='is_historical',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='sova_candidate_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='testprocess',
            name='is_historical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testprocess',
            name='source',
            field=models.CharField(choices=[('talena', 'Created in Talena'), ('sova_import', 'Imported from SOVA')], default='talena', max_length=50),
        ),
        migrations.AddField(
            model_name='testprocess',
            name='sova_account_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='testprocess',
            name='sova_import_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testprocess',
            name='sova_project_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='testprocess',
            name='sova_sync_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='testinvitation',
            name='source',
            field=models.CharField(choices=[('invited', 'Invited'), ('self_registered', 'Self-registered'), ('historical', 'Historical')], default='invited', max_length=20),
        ),
    ]
