# Generated by Django 6.0.1 on 2026-06-03 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0027_historicalcandidatereport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcandidatereport',
            name='invitation',
        ),
        migrations.CreateModel(
            name='HistoricalProcessCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('started', 'Started'), ('created', 'Created / unknown')], default='completed', max_length=50)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sova_candidate_id', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_process_records', to='processes.candidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_historical_process_candidates', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_candidates', to='processes.testprocess')),
            ],
            options={
                'ordering': ['candidate__last_name', 'candidate__first_name', '-created_at'],
                'unique_together': {('process', 'candidate', 'sova_candidate_id')},
            },
        ),
        migrations.AddField(
            model_name='historicalcandidatereport',
            name='historical_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='processes.historicalprocesscandidate'),
        ),
    ]
