# Generated by Django 5.2.9 on 2026-06-11 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0028_remove_historicalcandidatereport_invitation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAssessmentImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='historical_assessment_imports/')),
                ('original_filename', models.CharField(max_length=255)),
                ('assessment_type', models.CharField(blank=True, max_length=50)),
                ('scale', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='uploaded', max_length=50)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('candidates_created', models.PositiveIntegerField(default=0)),
                ('results_created', models.PositiveIntegerField(default=0)),
                ('scores_created', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_imports', to='processes.testprocess')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_assessment_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(max_length=50)),
                ('scale', models.CharField(blank=True, max_length=50)),
                ('sova_candidate_id', models.CharField(blank=True, max_length=100)),
                ('sova_result_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('time_added', models.DateTimeField(blank=True, null=True)),
                ('time_completed', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_assessment_results', to='processes.candidate')),
                ('historical_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='processes.historicalprocesscandidate')),
                ('import_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='processes.historicalassessmentimport')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_assessment_results', to='processes.testprocess')),
            ],
            options={
                'ordering': ['candidate__last_name', 'candidate__first_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('scale', models.CharField(blank=True, max_length=50)),
                ('score', models.FloatField(blank=True, null=True)),
                ('percentile', models.FloatField(blank=True, null=True)),
                ('raw_value', models.CharField(blank=True, max_length=255)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='processes.historicalassessmentresult')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='historicalassessmentresult',
            constraint=models.UniqueConstraint(fields=('process', 'candidate', 'assessment_type', 'scale', 'sova_result_id'), name='unique_historical_assessment_result'),
        ),
        migrations.AddConstraint(
            model_name='historicalassessmentscore',
            constraint=models.UniqueConstraint(fields=('result', 'name', 'category', 'scale'), name='unique_historical_assessment_score'),
        ),
    ]
