# Generated by Django 5.2.9 on 2026-06-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0029_historicalassessmentimport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrolecontext',
            name='purpose_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
