# Generated by Django 6.0.1 on 2026-06-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0030_processrolecontext_purpose_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinvitation',
            name='ai_purpose_fit',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_purpose_fit_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_purpose_fit_purpose',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_purpose_fit_status',
            field=models.CharField(blank=True, default='not_started', max_length=30),
        ),
    ]
