# Generated by Django 6.0.1 on 2026-06-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0031_testinvitation_ai_purpose_fit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocesscandidate',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalprocesscandidate',
            name='ai_summary_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('generating', 'Generating'), ('completed', 'Completed'), ('outdated', 'Outdated'), ('failed', 'Failed')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalprocesscandidate',
            name='ai_summary_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
