# Generated by Django 6.0.1 on 2026-06-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0032_historicalprocesscandidate_ai_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalprocesscandidate',
            old_name='ai_summary_updated_at',
            new_name='ai_summary_generated_at',
        ),
    ]
