# Generated by Django 5.2.9 on 2026-07-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0033_rename_ai_summary_updated_at_historicalprocesscandidate_ai_summary_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocesscandidate',
            name='ai_response_style_guidance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historicalprocesscandidate',
            name='ai_response_style_guidance_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprocesscandidate',
            name='ai_response_style_guidance_purpose',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalprocesscandidate',
            name='ai_response_style_guidance_status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not started'), ('generating', 'Generating'), ('completed', 'Completed'), ('outdated', 'Outdated'), ('failed', 'Failed')], default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_response_style_guidance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_response_style_guidance_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_response_style_guidance_purpose',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_response_style_guidance_status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not started'), ('generating', 'Generating'), ('completed', 'Completed'), ('outdated', 'Outdated'), ('failed', 'Failed')], default='not_started', max_length=30),
        ),
    ]
