# Generated by Django 5.2.9 on 2026-07-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0035_historicalprocesscandidate_ai_cognitive_interpretation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocesscandidate',
            name='ai_motivation_interpretation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historicalprocesscandidate',
            name='ai_motivation_interpretation_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprocesscandidate',
            name='ai_motivation_interpretation_purpose',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalprocesscandidate',
            name='ai_motivation_interpretation_status',
            field=models.CharField(blank=True, default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_motivation_interpretation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_motivation_interpretation_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_motivation_interpretation_purpose',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_motivation_interpretation_status',
            field=models.CharField(blank=True, default='not_started', max_length=30),
        ),
    ]
