# Generated by Django 5.2.9 on 2026-07-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0036_historicalprocesscandidate_ai_motivation_interpretation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocesscandidate',
            name='ai_personality_questions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historicalprocesscandidate',
            name='ai_personality_questions_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprocesscandidate',
            name='ai_personality_questions_purpose',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalprocesscandidate',
            name='ai_personality_questions_status',
            field=models.CharField(blank=True, default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalprocesscandidate',
            name='selected_personality_traits',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
