# Generated by Django 6.0.1 on 2026-07-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0038_testinvitation_ai_personality_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrolecontext',
            name='context_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
