# Generated by Django 6.0.1 on 2026-07-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0040_testinvitation_ai_personality_interpretation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocesscandidate',
            name='ai_personality_interpretation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historicalprocesscandidate',
            name='ai_personality_interpretation_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprocesscandidate',
            name='ai_personality_interpretation_purpose',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalprocesscandidate',
            name='ai_personality_interpretation_status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not started'), ('generating', 'Generating'), ('completed', 'Completed'), ('outdated', 'Outdated'), ('failed', 'Failed')], default='not_started', max_length=30),
        ),
    ]
