# Generated by Django 5.2.9 on 2026-07-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0041_historicalprocesscandidate_ai_personality_interpretation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinvitation',
            name='ai_cognitive_questions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_cognitive_questions_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_cognitive_questions_purpose',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_cognitive_questions_status',
            field=models.CharField(blank=True, default='not_started', max_length=30),
        ),
    ]
