# Generated by Django 5.2.9 on 2026-07-19 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0042_testinvitation_ai_cognitive_questions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testinvitation',
            name='ai_post_interview_decision_support',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_post_interview_decision_support_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_post_interview_decision_support_notes_version',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_post_interview_decision_support_purpose',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_post_interview_decision_support_status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not started'), ('generating', 'Generating'), ('completed', 'Completed'), ('outdated', 'Outdated'), ('failed', 'Failed')], default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_pre_interview_decision_support',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_pre_interview_decision_support_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_pre_interview_decision_support_purpose',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='ai_pre_interview_decision_support_status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not started'), ('generating', 'Generating'), ('completed', 'Completed'), ('outdated', 'Outdated'), ('failed', 'Failed')], default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='interview_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='interview_notes_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testinvitation',
            name='interview_notes_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_interview_notes_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
