# Generated by Django 6.0.1 on 2026-07-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0045_testinvitation_ai_motivation_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinvitation',
            name='ai_content_languages',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
