# Generated by Django 5.2.9 on 2026-07-25 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0046_testinvitation_ai_content_languages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Stable technical key used by the application, for example personality_interpretation.', max_length=100)),
                ('name', models.CharField(help_text='Human-readable name shown to administrators.', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Explain what this prompt controls and where the generated content is displayed.')),
                ('language', models.CharField(choices=[('sv', 'Swedish'), ('en', 'English')], default='sv', max_length=10)),
                ('prompt_text', models.TextField(help_text='Editable instructions for tone, focus, length and interpretation style.')),
                ('is_active', models.BooleanField(default=True, help_text='When inactive, Talena will fall back to the protected default prompt in the code.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ai_prompt_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI prompt',
                'verbose_name_plural': 'AI prompts',
                'ordering': ['name', 'language'],
                'constraints': [models.UniqueConstraint(fields=('key', 'language'), name='unique_ai_prompt_key_language')],
            },
        ),
    ]
