# Generated by Django 6.0.1 on 2026-07-25 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_role'),
        ('processes', '0047_aiprompttemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('personality', 'Personality'), ('motivation', 'Motivation'), ('verbal', 'Verbal'), ('logical', 'Logical'), ('numerical', 'Numerical'), ('other', 'Other')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('started', 'Started'), ('completed', 'Completed')], db_index=True, default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sova_request_id', models.CharField(blank=True, db_index=True, default='', max_length=512)),
                ('sova_activity_id', models.CharField(blank=True, default='', max_length=255)),
                ('sova_activity_name', models.CharField(blank=True, default='', max_length=255)),
                ('billing_excluded', models.BooleanField(db_index=True, default=False, help_text='Exclude this assessment from billing even if completed.')),
                ('billing_exclusion_reason', models.CharField(blank=True, default='', max_length=255)),
                ('company_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('org_unit_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('process_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('project_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('candidate_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('candidate_email_snapshot', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_usages', to='processes.candidate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_usages', to='accounts.company')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_usages', to='processes.testinvitation')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_usages', to='accounts.orgunit')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_usages', to='processes.testprocess')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_usages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at', '-sent_at', '-created_at'],
                'indexes': [models.Index(fields=['company', 'completed_at'], name='processes_a_company_23d84a_idx'), models.Index(fields=['company', 'sent_at'], name='processes_a_company_7002e9_idx'), models.Index(fields=['process', 'assessment_type'], name='processes_a_process_c64a05_idx'), models.Index(fields=['status', 'completed_at'], name='processes_a_status_6e334a_idx')],
                'constraints': [models.UniqueConstraint(fields=('invitation', 'assessment_type'), name='uniq_assessment_usage_invitation_type')],
            },
        ),
    ]
