# Generated by Django 6.0.1 on 2026-07-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0048_assessmentusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentusage',
            name='completed_at_is_estimated',
            field=models.BooleanField(db_index=True, default=False, help_text='True when completed_at is based on an invitation-level historical timestamp rather than an individual assessment completion event.'),
        ),
    ]
