# Generated by Django 6.0.1 on 2026-01-22 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processes', '0007_testinvitation_assessment_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(max_length=50)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body_snapshot', models.TextField()),
                ('status', models.CharField(default='queued', max_length=30)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='processes.testinvitation')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('invitation', 'Invitation'), ('reminder', 'Reminder'), ('completion', 'Completion')], max_length=50)),
                ('language', models.CharField(choices=[('sv', 'Swedish'), ('en', 'English')], default='sv', max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Use placeholders like {first_name}, {process_name}, {assessment_url}')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='processes.testprocess')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('process', 'template_type', 'language'), name='uniq_template_per_process_type_lang')],
            },
        ),
    ]
